=== Stuyk/altv-athena/src/altv_tplift_hopital/schema/config.schema.json
{
	"$schema": "http://json-schema.org/schema",
	"required": [
		"key",
		"areas"
	],
	"definitions": {
		"vector": {
			"required": [
				"x",
				"y",
				"z"
			],
			"type": "object",
			"properties": {
				"x": {
					"type": "number"
				},
				"y": {
					"type": "number"
				},
				"z": {
					"type": "number"
				}
			}
		},
		"color": {
			"required": [
				"r",
				"g",
				"b",
				"a"
			],
			"type": "object",
			"properties": {
				"r": {
					"type": "number",
					"minimum": 0,
					"maximum": 255
				},
				"g": {
					"type": "number",
					"minimum": 0,
					"maximum": 255
				},
				"b": {
					"type": "number",
					"minimum": 0,
					"maximum": 255
				},
				"a": {
					"type": "number",
					"minimum": 0,
					"maximum": 255
				}
			}
		}
	},
	"properties": {
		"distanceRenderMarker": {
			"type": "number",
			"minimum": 1,
			"maximum": 300
		},
		"key": {
			"type": "string"
		},
		"dimension": {
			"type": "number"
		},
		"areas": {
			"type": "array",
			"default": [],
			"items": {
				"type": "object",
				"required": [
					"marker",
					"spawn",
					"id"
				],
				"properties": {
					"id": {
						"type": "string"
					},
					"marker": {
						"type": "object",
						"required": [
							"size",
							"color",
							"type",
							"heading",
							"pos"
						],
						"properties": {
							"size": {
								"$ref": "#/definitions/vector"
							},
							"color": {
								"$ref": "#/definitions/color"
							},
							"type": {
								"type": "number",
								"pattern": "/[0-9]+/"
							},
							"heading": {
								"type": "number"
							},
							"pos": {
								"$ref": "#/definitions/vector"
							}
						}
					},
					"spawn": {
						"$ref": "#/definitions/vector"
					},
					"canGoTo": {
						"type": "array",
						"default": [],
						"items": {
							"type": "string"
						}
					}
				}
			}
		}
	}
}

=== Stuyk/altv-athena/src/altv_tplift_hopital/config.example.json
{
	"key": "E",
	"dimension": 0,
	"distanceRenderMarker": 15,
	"areas": [
		{
			"id": "Entrance1",
			"marker": {
				"pos": {
					"x": 0,
					"y": 0,
					"z": 70
				},
				"color": {
					"r": 255,
					"g": 187,
					"b": 255,
					"a": 255
				},
				"size": {
					"x": 2.0,
					"y": 2.0,
					"z": 1.0
				},
				"heading": 169.59108,
				"type": 1
			},
			"spawn": {
				"x": 0,
				"y": 0,
				"z": 73
			},
			"canGoTo": [
				"Room1"
			]
		},
		{
			"id": "Room1",
			"marker": {
				"pos": {
					"x": 0,
					"y": 10,
					"z": 70
				},
				"color": {
					"r": 255,
					"g": 187,
					"b": 255,
					"a": 255
				},
				"size": {
					"x": 2.0,
					"y": 2.0,
					"z": 1.0
				},
				"heading": 169.59108,
				"type": 1
			},
			"spawn": {
				"x": 0,
				"y": 10,
				"z": 73
			}
		}
	]
}
